# https://github.com/marketplace/actions/labeler

📦 configs:
  - 'libs/*config*/**/*'
  - 'libs/prettier/**/*'
🗜 nx:
  - 'nx.json'
  - 'workspace.json'
  - 'tools/plugins/**/*'
🗜 repo-scripts:
  - 'tools/scripts/**/*'
