---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template for the deploy-storybook.yml workflow action.

Resources:

  AllStorybooks:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: com-gu-all-storybooks
      WebsiteConfiguration:
        IndexDocument: index.html
  StorybookSourceFoundations:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: com-gu-storybook-source-foundations
      WebsiteConfiguration:
        IndexDocument: index.html
  StorybookSourceReactComponents:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: com-gu-storybook-source-react-components
      WebsiteConfiguration:
        IndexDocument: index.html
  StorybookSourceReactComponentsDevelopmentKitchen:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: com-gu-storybook-source-react-components-development
      WebsiteConfiguration:
        IndexDocument: index.html

  # Cloudfront is required for HTTPS unfortunately
  StorybookSourceFoundationsCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: bucket
            DomainName: !GetAtt StorybookSourceFoundations.DomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: bucket
          CachePolicyId: CachingOptimized
          ViewerProtocolPolicy: redirect-to-https
  StorybookSourceReactComponentsCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: bucket
            DomainName: !GetAtt StorybookSourceReactComponents.DomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: bucket
          CachePolicyId: CachingOptimized
          ViewerProtocolPolicy: redirect-to-https
  StorybookSourceReactComponentsDevelopmentKitchenCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: bucket
            DomainName: !GetAtt StorybookSourceReactComponentsDevelopmentKitchen.DomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: bucket
          CachePolicyId: CachingOptimized
          ViewerProtocolPolicy: redirect-to-https
