name: Manage Changesets

on:
  push:
    branches:
      - main

env:
  NX_BRANCH: ${{ github.event.pull_request.head.ref }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  changesets-version:
    name: Manage Changesets Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can
          # generate changelogs with the correct commits
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2
      - uses: pnpm/action-setup@v2.2.2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm nx nx affected --target=build

      # The Nx convention is to build packages to a root `dist` directory, but
      # changesets expects `dist` and `package.json` to live alongside the `src`
      # files in the standard workspace.
      #
      # Therefore, after building the packages we are going to publish, we will
      # rewrite the pnpm workspace file to point to the root `dist` directory instead.
      #
      # This will allow changesets to find the newly built assets to publish.
      #
      # https://dev.to/jmcdo29/automating-your-package-deployment-in-an-nx-monorepo-with-changeset-4em8
      - name: Prepare workspace for publishing
      - run: sed -e "s|'libs\/|'dist/|" pnpm-workspace.yaml > pnpm-new.yaml && \
          mv pnpm-new.yaml pnpm-workspace.yaml

      # down to business...
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
          title: '🦋 Release package updates'
          commit: 'Bump package versions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
